# Generated by Django 5.2.5 on 2025-09-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-pub_date'], 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem'),
        ),
    ]
