# Generated by Django 5.2.5 on 2025-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_deck_options_alter_problem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='body',
            field=models.TextField(),
        ),
    ]
