# Generated by Django 5.2.5 on 2025-09-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_hint_body_alter_problem_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='title',
        ),
    ]
