# Generated by Django 5.2.5 on 2025-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='book_page_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='book_problem_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='youtube_video_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
