# Generated by Django 5.2.5 on 2025-09-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_book_page_number_problem_book_problem_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSource',
        ),
        migrations.DeleteModel(
            name='PersonSource',
        ),
        migrations.DeleteModel(
            name='YouTubeVideoSource',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='book_page_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='book_problem_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source_content_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source_object_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='youtube_video_timestamp',
        ),
    ]
