# Generated by Django 5.2.5 on 2025-09-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_delete_booksource_delete_personsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='book_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.booksource'),
        ),
    ]
